# Generated by Django 3.2.13 on 2022-07-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
    ]
